# Generated by Django 4.1 on 2023-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=200)),
                ("Password", models.CharField(max_length=200)),
                ("ConfirmPassword", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="School",
        ),
    ]
